services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    develop:
      watch:
        - path: ./auth/
          target: /app/
          action: sync
        - path: ./auth/package.json
          action: rebuild
    depends_on:
      - mongodb
    env_file:
      - ./auth/.env
  
  product:
    build:
      context: ./product
      dockerfile: Dockerfile
    container_name: product
    develop:
      watch:
        - path: ./product/
          target: /app/
          action: sync
        - path: ./product/package.json
          action: rebuild
    depends_on:
      - mongodb
    env_file:
      - ./product/.env

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    develop:
      watch:
        - path: ./api-gateway/
          target: /app/
          action: sync
        - path: ./api-gateway/package.json
          action: rebuild
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - product
    env_file:
      - ./api-gateway/.env

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_auth:/data/db

volumes:
  mongodb_auth: